version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run:
          command: |
            go test -v ./operator/... -test.short
            go test -v ./backends/... -test.short