version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          command: |
            go test -v ./operator/... -test.short
      - run:
          command: |
            go test -v ./testutil/...