apiVersion: ensembleoss.io/v1
kind: Cluster
metadata:
  name: victoriametrics-simple
spec:
  backend:
    name: victoriametrics
  groups:
    - type: storage
      replicas: 2
    - type: insert
      replicas: 2
    - type: select
      replicas: 2