apiVersion: v1
entries:
  ensemble-operator:
  - apiVersion: v2
    created: "2021-07-30T20:40:37.1489284+02:00"
    description: 'Modular Kubernetes operator to manage the lifecycle of databases '
    digest: 04d1db1f4cd07df26d17b3adf71b7c30f85d998ed2d94a2df5b927478d5160a2
    home: https://ensembleoss.io
    maintainers:
    - name: Tesera
      url: https://tesera.io
    name: ensemble-operator
    type: application
    urls:
    - ensemble-operator-0.1.3.tgz
    version: 0.1.3
generated: "2021-07-30T20:40:37.147842443+02:00"
