// Code generated by "stringer -type=ScalarType -output=types_string.go"; DO NOT EDIT.

package schema

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeString-0]
	_ = x[TypeInt-1]
	_ = x[TypeBool-2]
}

const _ScalarType_name = "TypeStringTypeIntTypeBool"

var _ScalarType_index = [...]uint8{0, 10, 17, 25}

func (i ScalarType) String() string {
	if i < 0 || i >= ScalarType(len(_ScalarType_index)-1) {
		return "ScalarType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ScalarType_name[_ScalarType_index[i]:_ScalarType_index[i+1]]
}
