// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: operator/proto/structs.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Component_Status int32

const (
	Component_UNKNOWN  Component_Status = 0
	Component_PENDING  Component_Status = 1
	Component_QUEUED   Component_Status = 2
	Component_FAILED   Component_Status = 3
	Component_APPLIED  Component_Status = 4
	Component_CANCELED Component_Status = 5
)

// Enum value maps for Component_Status.
var (
	Component_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "QUEUED",
		3: "FAILED",
		4: "APPLIED",
		5: "CANCELED",
	}
	Component_Status_value = map[string]int32{
		"UNKNOWN":  0,
		"PENDING":  1,
		"QUEUED":   2,
		"FAILED":   3,
		"APPLIED":  4,
		"CANCELED": 5,
	}
)

func (x Component_Status) Enum() *Component_Status {
	p := new(Component_Status)
	*p = x
	return p
}

func (x Component_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Component_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_proto_structs_proto_enumTypes[0].Descriptor()
}

func (Component_Status) Type() protoreflect.EnumType {
	return &file_operator_proto_structs_proto_enumTypes[0]
}

func (x Component_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Component_Status.Descriptor instead.
func (Component_Status) EnumDescriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{3, 0}
}

type Component_Action int32

const (
	Component_NONE   Component_Action = 0
	Component_CREATE Component_Action = 1
	Component_DELETE Component_Action = 2
)

// Enum value maps for Component_Action.
var (
	Component_Action_name = map[int32]string{
		0: "NONE",
		1: "CREATE",
		2: "DELETE",
	}
	Component_Action_value = map[string]int32{
		"NONE":   0,
		"CREATE": 1,
		"DELETE": 2,
	}
)

func (x Component_Action) Enum() *Component_Action {
	p := new(Component_Action)
	*p = x
	return p
}

func (x Component_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Component_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_proto_structs_proto_enumTypes[1].Descriptor()
}

func (Component_Action) Type() protoreflect.EnumType {
	return &file_operator_proto_structs_proto_enumTypes[1]
}

func (x Component_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Component_Action.Descriptor instead.
func (Component_Action) EnumDescriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{3, 1}
}

type InstanceUpdate_StatusChange_Status int32

const (
	InstanceUpdate_StatusChange_FAILED InstanceUpdate_StatusChange_Status = 0
)

// Enum value maps for InstanceUpdate_StatusChange_Status.
var (
	InstanceUpdate_StatusChange_Status_name = map[int32]string{
		0: "FAILED",
	}
	InstanceUpdate_StatusChange_Status_value = map[string]int32{
		"FAILED": 0,
	}
)

func (x InstanceUpdate_StatusChange_Status) Enum() *InstanceUpdate_StatusChange_Status {
	p := new(InstanceUpdate_StatusChange_Status)
	*p = x
	return p
}

func (x InstanceUpdate_StatusChange_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceUpdate_StatusChange_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_proto_structs_proto_enumTypes[2].Descriptor()
}

func (InstanceUpdate_StatusChange_Status) Type() protoreflect.EnumType {
	return &file_operator_proto_structs_proto_enumTypes[2]
}

func (x InstanceUpdate_StatusChange_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceUpdate_StatusChange_Status.Descriptor instead.
func (InstanceUpdate_StatusChange_Status) EnumDescriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{8, 0, 0}
}

type Instance_Status int32

const (
	Instance_PENDING Instance_Status = 0
	Instance_FAILED  Instance_Status = 1
	Instance_OUT     Instance_Status = 2
	Instance_RUNNING Instance_Status = 3
	Instance_TAINTED Instance_Status = 4
)

// Enum value maps for Instance_Status.
var (
	Instance_Status_name = map[int32]string{
		0: "PENDING",
		1: "FAILED",
		2: "OUT",
		3: "RUNNING",
		4: "TAINTED",
	}
	Instance_Status_value = map[string]int32{
		"PENDING": 0,
		"FAILED":  1,
		"OUT":     2,
		"RUNNING": 3,
		"TAINTED": 4,
	}
)

func (x Instance_Status) Enum() *Instance_Status {
	p := new(Instance_Status)
	*p = x
	return p
}

func (x Instance_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Instance_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_proto_structs_proto_enumTypes[3].Descriptor()
}

func (Instance_Status) Type() protoreflect.EnumType {
	return &file_operator_proto_structs_proto_enumTypes[3]
}

func (x Instance_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Instance_Status.Descriptor instead.
func (Instance_Status) EnumDescriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{9, 0}
}

type Evaluation_Status int32

const (
	Evaluation_PENDING   Evaluation_Status = 0
	Evaluation_COMPLETE  Evaluation_Status = 1
	Evaluation_FAILED    Evaluation_Status = 2
	Evaluation_CANCELLED Evaluation_Status = 3
)

// Enum value maps for Evaluation_Status.
var (
	Evaluation_Status_name = map[int32]string{
		0: "PENDING",
		1: "COMPLETE",
		2: "FAILED",
		3: "CANCELLED",
	}
	Evaluation_Status_value = map[string]int32{
		"PENDING":   0,
		"COMPLETE":  1,
		"FAILED":    2,
		"CANCELLED": 3,
	}
)

func (x Evaluation_Status) Enum() *Evaluation_Status {
	p := new(Evaluation_Status)
	*p = x
	return p
}

func (x Evaluation_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Evaluation_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_proto_structs_proto_enumTypes[4].Descriptor()
}

func (Evaluation_Status) Type() protoreflect.EnumType {
	return &file_operator_proto_structs_proto_enumTypes[4]
}

func (x Evaluation_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Evaluation_Status.Descriptor instead.
func (Evaluation_Status) EnumDescriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{10, 0}
}

type Evaluation_Trigger int32

const (
	Evaluation_UNKNOWN    Evaluation_Trigger = 0
	Evaluation_SPECCHANGE Evaluation_Trigger = 1
	Evaluation_NODECHANGE Evaluation_Trigger = 2
)

// Enum value maps for Evaluation_Trigger.
var (
	Evaluation_Trigger_name = map[int32]string{
		0: "UNKNOWN",
		1: "SPECCHANGE",
		2: "NODECHANGE",
	}
	Evaluation_Trigger_value = map[string]int32{
		"UNKNOWN":    0,
		"SPECCHANGE": 1,
		"NODECHANGE": 2,
	}
)

func (x Evaluation_Trigger) Enum() *Evaluation_Trigger {
	p := new(Evaluation_Trigger)
	*p = x
	return p
}

func (x Evaluation_Trigger) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Evaluation_Trigger) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_proto_structs_proto_enumTypes[5].Descriptor()
}

func (Evaluation_Trigger) Type() protoreflect.EnumType {
	return &file_operator_proto_structs_proto_enumTypes[5]
}

func (x Evaluation_Trigger) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Evaluation_Trigger.Descriptor instead.
func (Evaluation_Trigger) EnumDescriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{10, 1}
}

type ListDeploymentsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deployments []*Deployment `protobuf:"bytes,1,rep,name=deployments,proto3" json:"deployments,omitempty"`
}

func (x *ListDeploymentsResp) Reset() {
	*x = ListDeploymentsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDeploymentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeploymentsResp) ProtoMessage() {}

func (x *ListDeploymentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeploymentsResp.ProtoReflect.Descriptor instead.
func (*ListDeploymentsResp) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{0}
}

func (x *ListDeploymentsResp) GetDeployments() []*Deployment {
	if x != nil {
		return x.Deployments
	}
	return nil
}

type GetDeploymentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cluster string `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
}

func (x *GetDeploymentReq) Reset() {
	*x = GetDeploymentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDeploymentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeploymentReq) ProtoMessage() {}

func (x *GetDeploymentReq) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeploymentReq.ProtoReflect.Descriptor instead.
func (*GetDeploymentReq) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{1}
}

func (x *GetDeploymentReq) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

type ComponentTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Old *Component `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New *Component `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
}

func (x *ComponentTask) Reset() {
	*x = ComponentTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComponentTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentTask) ProtoMessage() {}

func (x *ComponentTask) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentTask.ProtoReflect.Descriptor instead.
func (*ComponentTask) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{2}
}

func (x *ComponentTask) GetOld() *Component {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *ComponentTask) GetNew() *Component {
	if x != nil {
		return x.New
	}
	return nil
}

// Component is like a snapshot or something. AKA Evaluation
type Component struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id of the component
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// name is the name of the component
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// spec of the stuff being applied
	Spec *any.Any `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	// generation of the component
	Sequence int64 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// status of the component
	Status Component_Status `protobuf:"varint,5,opt,name=status,proto3,enum=proto.Component_Status" json:"status,omitempty"`
	// Type of action
	Action Component_Action `protobuf:"varint,6,opt,name=action,proto3,enum=proto.Component_Action" json:"action,omitempty"`
	// timestamp
	Timestamp *timestamp.Timestamp `protobuf:"bytes,7,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	// metadata of the component
	Metadata map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Component) Reset() {
	*x = Component{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Component) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Component) ProtoMessage() {}

func (x *Component) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Component.ProtoReflect.Descriptor instead.
func (*Component) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{3}
}

func (x *Component) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Component) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Component) GetSpec() *any.Any {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Component) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Component) GetStatus() Component_Status {
	if x != nil {
		return x.Status
	}
	return Component_UNKNOWN
}

func (x *Component) GetAction() Component_Action {
	if x != nil {
		return x.Action
	}
	return Component_NONE
}

func (x *Component) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Component) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Description of the cluster
type ClusterSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// name of the backend
	Backend string `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	// version of the backend (RESERVED)
	Version  string               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Groups   []*ClusterSpec_Group `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	Sequence int64                `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *ClusterSpec) Reset() {
	*x = ClusterSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSpec) ProtoMessage() {}

func (x *ClusterSpec) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSpec.ProtoReflect.Descriptor instead.
func (*ClusterSpec) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{4}
}

func (x *ClusterSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterSpec) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *ClusterSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ClusterSpec) GetGroups() []*ClusterSpec_Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ClusterSpec) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Description of the resource
type ResourceSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the cluster
	Cluster string `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// name of the resource in the backend
	Resource string `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	// params are the params to configure the resource (in JSON)
	Params string `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceSpec) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *ResourceSpec) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ResourceSpec) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

// This is not important to keep on the Instance stored since we can rebuild this at any
// time because the function Initialize is deterministic??
// This represents all the things required to Create the resource
type NodeSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// PROVISIONAL
	Image   string            `protobuf:"bytes,30,opt,name=image,proto3" json:"image,omitempty"`
	Version string            `protobuf:"bytes,31,opt,name=version,proto3" json:"version,omitempty"`
	Env     map[string]string `protobuf:"bytes,1,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Files   map[string]string `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cmd     []string          `protobuf:"bytes,5,rep,name=cmd,proto3" json:"cmd,omitempty"`
}

func (x *NodeSpec) Reset() {
	*x = NodeSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSpec) ProtoMessage() {}

func (x *NodeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSpec.ProtoReflect.Descriptor instead.
func (*NodeSpec) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{6}
}

func (x *NodeSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *NodeSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *NodeSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *NodeSpec) GetFiles() map[string]string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *NodeSpec) GetCmd() []string {
	if x != nil {
		return x.Cmd
	}
	return nil
}

type Deployment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Instances []*Instance                       `protobuf:"bytes,2,rep,name=instances,proto3" json:"instances,omitempty"`
	Groups    map[string]*Deployment_GroupState `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Status    string                            `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Sequence  int64                             `protobuf:"varint,5,opt,name=sequence,proto3" json:"sequence,omitempty"`
	CompID    string                            `protobuf:"bytes,6,opt,name=compID,proto3" json:"compID,omitempty"`
	Backend   string                            `protobuf:"bytes,7,opt,name=backend,proto3" json:"backend,omitempty"`
}

func (x *Deployment) Reset() {
	*x = Deployment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deployment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment) ProtoMessage() {}

func (x *Deployment) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment.ProtoReflect.Descriptor instead.
func (*Deployment) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{7}
}

func (x *Deployment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Deployment) GetInstances() []*Instance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *Deployment) GetGroups() map[string]*Deployment_GroupState {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Deployment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Deployment) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Deployment) GetCompID() string {
	if x != nil {
		return x.CompID
	}
	return ""
}

func (x *Deployment) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

type InstanceUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Cluster string `protobuf:"bytes,2,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	// Types that are assignable to Event:
	//	*InstanceUpdate_Conf
	//	*InstanceUpdate_Status
	Event isInstanceUpdate_Event `protobuf_oneof:"event"`
}

func (x *InstanceUpdate) Reset() {
	*x = InstanceUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstanceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceUpdate) ProtoMessage() {}

func (x *InstanceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceUpdate.ProtoReflect.Descriptor instead.
func (*InstanceUpdate) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{8}
}

func (x *InstanceUpdate) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *InstanceUpdate) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (m *InstanceUpdate) GetEvent() isInstanceUpdate_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *InstanceUpdate) GetConf() *InstanceUpdate_ConfDone {
	if x, ok := x.GetEvent().(*InstanceUpdate_Conf); ok {
		return x.Conf
	}
	return nil
}

func (x *InstanceUpdate) GetStatus() *InstanceUpdate_StatusChange {
	if x, ok := x.GetEvent().(*InstanceUpdate_Status); ok {
		return x.Status
	}
	return nil
}

type isInstanceUpdate_Event interface {
	isInstanceUpdate_Event()
}

type InstanceUpdate_Conf struct {
	Conf *InstanceUpdate_ConfDone `protobuf:"bytes,3,opt,name=conf,proto3,oneof"`
}

type InstanceUpdate_Status struct {
	Status *InstanceUpdate_StatusChange `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

func (*InstanceUpdate_Conf) isInstanceUpdate_Event() {}

func (*InstanceUpdate_Status) isInstanceUpdate_Event() {}

// represents a POD
type Instance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        string             `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name      string             `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Namespace string             `protobuf:"bytes,4,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Cluster   string             `protobuf:"bytes,3,opt,name=Cluster,proto3" json:"Cluster,omitempty"`
	Group     *ClusterSpec_Group `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Index     int64              `protobuf:"varint,7,opt,name=index,proto3" json:"index,omitempty"`
	KV        map[string]string  `protobuf:"bytes,10,rep,name=KV,proto3" json:"KV,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// PROVISIONAL
	Spec    *NodeSpec       `protobuf:"bytes,11,opt,name=spec,proto3" json:"spec,omitempty"`
	Status  Instance_Status `protobuf:"varint,12,opt,name=status,proto3,enum=proto.Instance_Status" json:"status,omitempty"`
	Desired string          `protobuf:"bytes,13,opt,name=desired,proto3" json:"desired,omitempty"`
	Canary  bool            `protobuf:"varint,14,opt,name=canary,proto3" json:"canary,omitempty"`
	Healthy bool            `protobuf:"varint,15,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Count   int64           `protobuf:"varint,22,opt,name=count,proto3" json:"count,omitempty"`
	Ip      string          `protobuf:"bytes,23,opt,name=ip,proto3" json:"ip,omitempty"`
	// previous instance if this is replacing another one
	Prev     string `protobuf:"bytes,24,opt,name=prev,proto3" json:"prev,omitempty"`
	Handler  string `protobuf:"bytes,25,opt,name=handler,proto3" json:"handler,omitempty"`
	Sequence int64  `protobuf:"varint,26,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *Instance) Reset() {
	*x = Instance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{9}
}

func (x *Instance) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Instance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Instance) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Instance) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *Instance) GetGroup() *ClusterSpec_Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *Instance) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Instance) GetKV() map[string]string {
	if x != nil {
		return x.KV
	}
	return nil
}

func (x *Instance) GetSpec() *NodeSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Instance) GetStatus() Instance_Status {
	if x != nil {
		return x.Status
	}
	return Instance_PENDING
}

func (x *Instance) GetDesired() string {
	if x != nil {
		return x.Desired
	}
	return ""
}

func (x *Instance) GetCanary() bool {
	if x != nil {
		return x.Canary
	}
	return false
}

func (x *Instance) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *Instance) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Instance) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Instance) GetPrev() string {
	if x != nil {
		return x.Prev
	}
	return ""
}

func (x *Instance) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *Instance) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type Evaluation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id of the evaluation
	Id          string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status      Evaluation_Status  `protobuf:"varint,2,opt,name=status,proto3,enum=proto.Evaluation_Status" json:"status,omitempty"`
	TriggeredBy Evaluation_Trigger `protobuf:"varint,3,opt,name=triggeredBy,proto3,enum=proto.Evaluation_Trigger" json:"triggeredBy,omitempty"`
	ClusterID   string             `protobuf:"bytes,4,opt,name=clusterID,proto3" json:"clusterID,omitempty"`
}

func (x *Evaluation) Reset() {
	*x = Evaluation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Evaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evaluation) ProtoMessage() {}

func (x *Evaluation) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evaluation.ProtoReflect.Descriptor instead.
func (*Evaluation) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{10}
}

func (x *Evaluation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Evaluation) GetStatus() Evaluation_Status {
	if x != nil {
		return x.Status
	}
	return Evaluation_PENDING
}

func (x *Evaluation) GetTriggeredBy() Evaluation_Trigger {
	if x != nil {
		return x.TriggeredBy
	}
	return Evaluation_UNKNOWN
}

func (x *Evaluation) GetClusterID() string {
	if x != nil {
		return x.ClusterID
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EvalID    string               `protobuf:"bytes,1,opt,name=evalID,proto3" json:"evalID,omitempty"`
	Message   string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details   map[string]string    `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp *timestamp.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{11}
}

func (x *Event) GetEvalID() string {
	if x != nil {
		return x.EvalID
	}
	return ""
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Event) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Event) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ClusterSpec_Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count     int64             `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Type      string            `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Config    map[string]string `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Resources map[string]string `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ClusterSpec_Group) Reset() {
	*x = ClusterSpec_Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClusterSpec_Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSpec_Group) ProtoMessage() {}

func (x *ClusterSpec_Group) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSpec_Group.ProtoReflect.Descriptor instead.
func (*ClusterSpec_Group) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ClusterSpec_Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClusterSpec_Group) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ClusterSpec_Group) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ClusterSpec_Group) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ClusterSpec_Group) GetResources() map[string]string {
	if x != nil {
		return x.Resources
	}
	return nil
}

type Deployment_GroupState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Desired int64 `protobuf:"varint,1,opt,name=desired,proto3" json:"desired,omitempty"` // not necessary
	Update  int64 `protobuf:"varint,2,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *Deployment_GroupState) Reset() {
	*x = Deployment_GroupState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deployment_GroupState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deployment_GroupState) ProtoMessage() {}

func (x *Deployment_GroupState) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deployment_GroupState.ProtoReflect.Descriptor instead.
func (*Deployment_GroupState) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{7, 1}
}

func (x *Deployment_GroupState) GetDesired() int64 {
	if x != nil {
		return x.Desired
	}
	return 0
}

func (x *Deployment_GroupState) GetUpdate() int64 {
	if x != nil {
		return x.Update
	}
	return 0
}

type InstanceUpdate_StatusChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status InstanceUpdate_StatusChange_Status `protobuf:"varint,1,opt,name=status,proto3,enum=proto.InstanceUpdate_StatusChange_Status" json:"status,omitempty"`
}

func (x *InstanceUpdate_StatusChange) Reset() {
	*x = InstanceUpdate_StatusChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstanceUpdate_StatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceUpdate_StatusChange) ProtoMessage() {}

func (x *InstanceUpdate_StatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceUpdate_StatusChange.ProtoReflect.Descriptor instead.
func (*InstanceUpdate_StatusChange) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{8, 0}
}

func (x *InstanceUpdate_StatusChange) GetStatus() InstanceUpdate_StatusChange_Status {
	if x != nil {
		return x.Status
	}
	return InstanceUpdate_StatusChange_FAILED
}

type InstanceUpdate_ConfDone struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip      string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Handler string `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler,omitempty"`
}

func (x *InstanceUpdate_ConfDone) Reset() {
	*x = InstanceUpdate_ConfDone{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operator_proto_structs_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstanceUpdate_ConfDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceUpdate_ConfDone) ProtoMessage() {}

func (x *InstanceUpdate_ConfDone) ProtoReflect() protoreflect.Message {
	mi := &file_operator_proto_structs_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceUpdate_ConfDone.ProtoReflect.Descriptor instead.
func (*InstanceUpdate_ConfDone) Descriptor() ([]byte, []int) {
	return file_operator_proto_structs_proto_rawDescGZIP(), []int{8, 1}
}

func (x *InstanceUpdate_ConfDone) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *InstanceUpdate_ConfDone) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

var File_operator_proto_structs_proto protoreflect.FileDescriptor

var file_operator_proto_structs_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a,
	0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0b, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x64,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x2c, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x22, 0x57, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x22, 0x0a, 0x03, 0x6f, 0x6c, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x52, 0x03, 0x6f, 0x6c, 0x64, 0x12, 0x22, 0x0a,
	0x03, 0x6e, 0x65, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x52, 0x03, 0x6e, 0x65,
	0x77, 0x22, 0x8d, 0x04, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x09, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x3a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x55,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x51, 0x55, 0x45, 0x55, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x50,
	0x50, 0x4c, 0x49, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x43, 0x41, 0x4e, 0x43, 0x45,
	0x4c, 0x45, 0x44, 0x10, 0x05, 0x22, 0x2a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45,
	0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10,
	0x02, 0x22, 0xe9, 0x03, 0x0a, 0x0b, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x06, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x1a, 0xc3, 0x02, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x3c, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x70, 0x65, 0x63, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x45, 0x0a,
	0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x53, 0x70, 0x65, 0x63, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a,
	0x3c, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x5c, 0x0a,
	0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x9c, 0x02, 0x0a, 0x08,
	0x4e, 0x6f, 0x64, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x03, 0x65, 0x6e, 0x76, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x03, 0x65, 0x6e, 0x76, 0x12, 0x30, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x53, 0x70, 0x65, 0x63, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x1a, 0x38, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x81, 0x03, 0x0a, 0x0a, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x09, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x09, 0x69,
	0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x70, 0x49, 0x44, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x70, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61,
	0x63, 0x6b, 0x65, 0x6e, 0x64, 0x1a, 0x57, 0x0a, 0x0b, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x32, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3e,
	0x0a, 0x0a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x64,
	0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0xd6,
	0x02, 0x0a, 0x0e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x04, 0x63,
	0x6f, 0x6e, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x44, 0x6f, 0x6e, 0x65, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6f, 0x6e,
	0x66, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a,
	0x67, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x41, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x14, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x00, 0x1a, 0x34, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x66,
	0x44, 0x6f, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x42, 0x07,
	0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0xe3, 0x04, 0x0a, 0x08, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x12, 0x2e, 0x0a, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x70, 0x65, 0x63, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x27, 0x0a, 0x02, 0x4b, 0x56, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x4b, 0x56, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x02, 0x4b, 0x56, 0x12,
	0x23, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04,
	0x73, 0x70, 0x65, 0x63, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x69, 0x72, 0x65, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x61, 0x6e, 0x61, 0x72, 0x79, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x63, 0x61, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x79, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x16, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x17, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x72, 0x65, 0x76, 0x18, 0x18,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x72, 0x65, 0x76, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x72, 0x18, 0x19, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x18, 0x1a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65,
	0x1a, 0x35, 0x0a, 0x07, 0x4b, 0x56, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x44, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x4f, 0x55,
	0x54, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x03,
	0x12, 0x0b, 0x0a, 0x07, 0x54, 0x41, 0x49, 0x4e, 0x54, 0x45, 0x44, 0x10, 0x04, 0x22, 0xa1, 0x02,
	0x0a, 0x0a, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x3b,
	0x0a, 0x0b, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x65, 0x64, 0x42, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x0b,
	0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x44, 0x22, 0x3e, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x41,
	0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x22, 0x36, 0x0a, 0x07, 0x54, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x50, 0x45, 0x43, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10,
	0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4e, 0x4f, 0x44, 0x45, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10,
	0x02, 0x22, 0xe4, 0x01, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x76, 0x61, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x76, 0x61,
	0x6c, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a,
	0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x1a, 0x3a, 0x0a, 0x0c,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xc2, 0x01, 0x0a, 0x0f, 0x45, 0x6e, 0x73,
	0x65, 0x6d, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x05,
	0x41, 0x70, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x45, 0x0a, 0x0f, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x3b, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x65, 0x70,
	0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x11, 0x5a,
	0x0f, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_operator_proto_structs_proto_rawDescOnce sync.Once
	file_operator_proto_structs_proto_rawDescData = file_operator_proto_structs_proto_rawDesc
)

func file_operator_proto_structs_proto_rawDescGZIP() []byte {
	file_operator_proto_structs_proto_rawDescOnce.Do(func() {
		file_operator_proto_structs_proto_rawDescData = protoimpl.X.CompressGZIP(file_operator_proto_structs_proto_rawDescData)
	})
	return file_operator_proto_structs_proto_rawDescData
}

var file_operator_proto_structs_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_operator_proto_structs_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_operator_proto_structs_proto_goTypes = []interface{}{
	(Component_Status)(0),                   // 0: proto.Component.Status
	(Component_Action)(0),                   // 1: proto.Component.Action
	(InstanceUpdate_StatusChange_Status)(0), // 2: proto.InstanceUpdate.StatusChange.Status
	(Instance_Status)(0),                    // 3: proto.Instance.Status
	(Evaluation_Status)(0),                  // 4: proto.Evaluation.Status
	(Evaluation_Trigger)(0),                 // 5: proto.Evaluation.Trigger
	(*ListDeploymentsResp)(nil),             // 6: proto.ListDeploymentsResp
	(*GetDeploymentReq)(nil),                // 7: proto.GetDeploymentReq
	(*ComponentTask)(nil),                   // 8: proto.ComponentTask
	(*Component)(nil),                       // 9: proto.Component
	(*ClusterSpec)(nil),                     // 10: proto.ClusterSpec
	(*ResourceSpec)(nil),                    // 11: proto.ResourceSpec
	(*NodeSpec)(nil),                        // 12: proto.NodeSpec
	(*Deployment)(nil),                      // 13: proto.Deployment
	(*InstanceUpdate)(nil),                  // 14: proto.InstanceUpdate
	(*Instance)(nil),                        // 15: proto.Instance
	(*Evaluation)(nil),                      // 16: proto.Evaluation
	(*Event)(nil),                           // 17: proto.Event
	nil,                                     // 18: proto.Component.MetadataEntry
	(*ClusterSpec_Group)(nil),               // 19: proto.ClusterSpec.Group
	nil,                                     // 20: proto.ClusterSpec.Group.ConfigEntry
	nil,                                     // 21: proto.ClusterSpec.Group.ResourcesEntry
	nil,                                     // 22: proto.NodeSpec.EnvEntry
	nil,                                     // 23: proto.NodeSpec.FilesEntry
	nil,                                     // 24: proto.Deployment.GroupsEntry
	(*Deployment_GroupState)(nil),           // 25: proto.Deployment.GroupState
	(*InstanceUpdate_StatusChange)(nil),     // 26: proto.InstanceUpdate.StatusChange
	(*InstanceUpdate_ConfDone)(nil),         // 27: proto.InstanceUpdate.ConfDone
	nil,                                     // 28: proto.Instance.KVEntry
	nil,                                     // 29: proto.Event.DetailsEntry
	(*any.Any)(nil),                         // 30: google.protobuf.Any
	(*timestamp.Timestamp)(nil),             // 31: google.protobuf.Timestamp
	(*empty.Empty)(nil),                     // 32: google.protobuf.Empty
}
var file_operator_proto_structs_proto_depIdxs = []int32{
	13, // 0: proto.ListDeploymentsResp.deployments:type_name -> proto.Deployment
	9,  // 1: proto.ComponentTask.old:type_name -> proto.Component
	9,  // 2: proto.ComponentTask.new:type_name -> proto.Component
	30, // 3: proto.Component.spec:type_name -> google.protobuf.Any
	0,  // 4: proto.Component.status:type_name -> proto.Component.Status
	1,  // 5: proto.Component.action:type_name -> proto.Component.Action
	31, // 6: proto.Component.Timestamp:type_name -> google.protobuf.Timestamp
	18, // 7: proto.Component.metadata:type_name -> proto.Component.MetadataEntry
	19, // 8: proto.ClusterSpec.groups:type_name -> proto.ClusterSpec.Group
	22, // 9: proto.NodeSpec.env:type_name -> proto.NodeSpec.EnvEntry
	23, // 10: proto.NodeSpec.files:type_name -> proto.NodeSpec.FilesEntry
	15, // 11: proto.Deployment.instances:type_name -> proto.Instance
	24, // 12: proto.Deployment.groups:type_name -> proto.Deployment.GroupsEntry
	27, // 13: proto.InstanceUpdate.conf:type_name -> proto.InstanceUpdate.ConfDone
	26, // 14: proto.InstanceUpdate.status:type_name -> proto.InstanceUpdate.StatusChange
	19, // 15: proto.Instance.group:type_name -> proto.ClusterSpec.Group
	28, // 16: proto.Instance.KV:type_name -> proto.Instance.KVEntry
	12, // 17: proto.Instance.spec:type_name -> proto.NodeSpec
	3,  // 18: proto.Instance.status:type_name -> proto.Instance.Status
	4,  // 19: proto.Evaluation.status:type_name -> proto.Evaluation.Status
	5,  // 20: proto.Evaluation.triggeredBy:type_name -> proto.Evaluation.Trigger
	29, // 21: proto.Event.details:type_name -> proto.Event.DetailsEntry
	31, // 22: proto.Event.timestamp:type_name -> google.protobuf.Timestamp
	20, // 23: proto.ClusterSpec.Group.config:type_name -> proto.ClusterSpec.Group.ConfigEntry
	21, // 24: proto.ClusterSpec.Group.resources:type_name -> proto.ClusterSpec.Group.ResourcesEntry
	25, // 25: proto.Deployment.GroupsEntry.value:type_name -> proto.Deployment.GroupState
	2,  // 26: proto.InstanceUpdate.StatusChange.status:type_name -> proto.InstanceUpdate.StatusChange.Status
	9,  // 27: proto.EnsembleService.Apply:input_type -> proto.Component
	32, // 28: proto.EnsembleService.ListDeployments:input_type -> google.protobuf.Empty
	7,  // 29: proto.EnsembleService.GetDeployment:input_type -> proto.GetDeploymentReq
	9,  // 30: proto.EnsembleService.Apply:output_type -> proto.Component
	6,  // 31: proto.EnsembleService.ListDeployments:output_type -> proto.ListDeploymentsResp
	13, // 32: proto.EnsembleService.GetDeployment:output_type -> proto.Deployment
	30, // [30:33] is the sub-list for method output_type
	27, // [27:30] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_operator_proto_structs_proto_init() }
func file_operator_proto_structs_proto_init() {
	if File_operator_proto_structs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_operator_proto_structs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDeploymentsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDeploymentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComponentTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Component); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deployment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstanceUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Instance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Evaluation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClusterSpec_Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deployment_GroupState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstanceUpdate_StatusChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operator_proto_structs_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstanceUpdate_ConfDone); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_operator_proto_structs_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*InstanceUpdate_Conf)(nil),
		(*InstanceUpdate_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_operator_proto_structs_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operator_proto_structs_proto_goTypes,
		DependencyIndexes: file_operator_proto_structs_proto_depIdxs,
		EnumInfos:         file_operator_proto_structs_proto_enumTypes,
		MessageInfos:      file_operator_proto_structs_proto_msgTypes,
	}.Build()
	File_operator_proto_structs_proto = out.File
	file_operator_proto_structs_proto_rawDesc = nil
	file_operator_proto_structs_proto_goTypes = nil
	file_operator_proto_structs_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EnsembleServiceClient is the client API for EnsembleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EnsembleServiceClient interface {
	Apply(ctx context.Context, in *Component, opts ...grpc.CallOption) (*Component, error)
	ListDeployments(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListDeploymentsResp, error)
	GetDeployment(ctx context.Context, in *GetDeploymentReq, opts ...grpc.CallOption) (*Deployment, error)
}

type ensembleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnsembleServiceClient(cc grpc.ClientConnInterface) EnsembleServiceClient {
	return &ensembleServiceClient{cc}
}

func (c *ensembleServiceClient) Apply(ctx context.Context, in *Component, opts ...grpc.CallOption) (*Component, error) {
	out := new(Component)
	err := c.cc.Invoke(ctx, "/proto.EnsembleService/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ensembleServiceClient) ListDeployments(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListDeploymentsResp, error) {
	out := new(ListDeploymentsResp)
	err := c.cc.Invoke(ctx, "/proto.EnsembleService/ListDeployments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ensembleServiceClient) GetDeployment(ctx context.Context, in *GetDeploymentReq, opts ...grpc.CallOption) (*Deployment, error) {
	out := new(Deployment)
	err := c.cc.Invoke(ctx, "/proto.EnsembleService/GetDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnsembleServiceServer is the server API for EnsembleService service.
type EnsembleServiceServer interface {
	Apply(context.Context, *Component) (*Component, error)
	ListDeployments(context.Context, *empty.Empty) (*ListDeploymentsResp, error)
	GetDeployment(context.Context, *GetDeploymentReq) (*Deployment, error)
}

// UnimplementedEnsembleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEnsembleServiceServer struct {
}

func (*UnimplementedEnsembleServiceServer) Apply(context.Context, *Component) (*Component, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apply not implemented")
}
func (*UnimplementedEnsembleServiceServer) ListDeployments(context.Context, *empty.Empty) (*ListDeploymentsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeployments not implemented")
}
func (*UnimplementedEnsembleServiceServer) GetDeployment(context.Context, *GetDeploymentReq) (*Deployment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeployment not implemented")
}

func RegisterEnsembleServiceServer(s *grpc.Server, srv EnsembleServiceServer) {
	s.RegisterService(&_EnsembleService_serviceDesc, srv)
}

func _EnsembleService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Component)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnsembleServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EnsembleService/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnsembleServiceServer).Apply(ctx, req.(*Component))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnsembleService_ListDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnsembleServiceServer).ListDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EnsembleService/ListDeployments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnsembleServiceServer).ListDeployments(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnsembleService_GetDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnsembleServiceServer).GetDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EnsembleService/GetDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnsembleServiceServer).GetDeployment(ctx, req.(*GetDeploymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _EnsembleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EnsembleService",
	HandlerType: (*EnsembleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _EnsembleService_Apply_Handler,
		},
		{
			MethodName: "ListDeployments",
			Handler:    _EnsembleService_ListDeployments_Handler,
		},
		{
			MethodName: "GetDeployment",
			Handler:    _EnsembleService_GetDeployment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operator/proto/structs.proto",
}
