// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EnsembleServiceClient is the client API for EnsembleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EnsembleServiceClient interface {
	Apply(ctx context.Context, in *Component, opts ...grpc.CallOption) (*Component, error)
	ListDeployments(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListDeploymentsResp, error)
	GetDeployment(ctx context.Context, in *GetDeploymentReq, opts ...grpc.CallOption) (*Deployment, error)
}

type ensembleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnsembleServiceClient(cc grpc.ClientConnInterface) EnsembleServiceClient {
	return &ensembleServiceClient{cc}
}

func (c *ensembleServiceClient) Apply(ctx context.Context, in *Component, opts ...grpc.CallOption) (*Component, error) {
	out := new(Component)
	err := c.cc.Invoke(ctx, "/proto.EnsembleService/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ensembleServiceClient) ListDeployments(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListDeploymentsResp, error) {
	out := new(ListDeploymentsResp)
	err := c.cc.Invoke(ctx, "/proto.EnsembleService/ListDeployments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ensembleServiceClient) GetDeployment(ctx context.Context, in *GetDeploymentReq, opts ...grpc.CallOption) (*Deployment, error) {
	out := new(Deployment)
	err := c.cc.Invoke(ctx, "/proto.EnsembleService/GetDeployment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnsembleServiceServer is the server API for EnsembleService service.
// All implementations must embed UnimplementedEnsembleServiceServer
// for forward compatibility
type EnsembleServiceServer interface {
	Apply(context.Context, *Component) (*Component, error)
	ListDeployments(context.Context, *empty.Empty) (*ListDeploymentsResp, error)
	GetDeployment(context.Context, *GetDeploymentReq) (*Deployment, error)
	mustEmbedUnimplementedEnsembleServiceServer()
}

// UnimplementedEnsembleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEnsembleServiceServer struct {
}

func (UnimplementedEnsembleServiceServer) Apply(context.Context, *Component) (*Component, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedEnsembleServiceServer) ListDeployments(context.Context, *empty.Empty) (*ListDeploymentsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDeployments not implemented")
}
func (UnimplementedEnsembleServiceServer) GetDeployment(context.Context, *GetDeploymentReq) (*Deployment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeployment not implemented")
}
func (UnimplementedEnsembleServiceServer) mustEmbedUnimplementedEnsembleServiceServer() {}

// UnsafeEnsembleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnsembleServiceServer will
// result in compilation errors.
type UnsafeEnsembleServiceServer interface {
	mustEmbedUnimplementedEnsembleServiceServer()
}

func RegisterEnsembleServiceServer(s grpc.ServiceRegistrar, srv EnsembleServiceServer) {
	s.RegisterService(&EnsembleService_ServiceDesc, srv)
}

func _EnsembleService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Component)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnsembleServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EnsembleService/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnsembleServiceServer).Apply(ctx, req.(*Component))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnsembleService_ListDeployments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnsembleServiceServer).ListDeployments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EnsembleService/ListDeployments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnsembleServiceServer).ListDeployments(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnsembleService_GetDeployment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeploymentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnsembleServiceServer).GetDeployment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EnsembleService/GetDeployment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnsembleServiceServer).GetDeployment(ctx, req.(*GetDeploymentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// EnsembleService_ServiceDesc is the grpc.ServiceDesc for EnsembleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnsembleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EnsembleService",
	HandlerType: (*EnsembleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _EnsembleService_Apply_Handler,
		},
		{
			MethodName: "ListDeployments",
			Handler:    _EnsembleService_ListDeployments_Handler,
		},
		{
			MethodName: "GetDeployment",
			Handler:    _EnsembleService_GetDeployment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operator/proto/structs.proto",
}
