---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ensemble.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ensemble.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "ensemble.serviceAccountName" . }}
  namespace: default
