apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ensemble.fullname" . }}
rules:
- apiGroups:
  - ensembleoss.io
  resources:
  - clusters
  - clusters/status
  - resources
  - resources/status
  verbs:
  - "*"
- apiGroups:
  - ''
  resources:
  - pods
  - pods/exec
  - services
  - endpoints
  - events
  - configmaps
  verbs:
  - "*"
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - '*'
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get