name: E2E tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-16.04
    name: Go test
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.15.10'
      - uses: AbsaOSS/k3d-action@v1.5.0
        name: "Create Single Cluster"
        with:
          cluster-name: "e2e-cluster"
          args: --agents 1
      - run: kubectl config use-context k3d-e2e-cluster
      - run: go mod vendor
      - name: Build docker
        run: make build-dev-docker
      - name: Upload dev image
        run: k3d image import ensemble:dev -c e2e-cluster --verbose
      - name: Test
        run: kubectl get pods